# Generated by Django 2.1.8 on 2021-04-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exammanagerrelation_can_create_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='short_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
