# Generated by Django 2.1.8 on 2021-04-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210404_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-id',)},
        ),
    ]
