# Generated by Django 3.1.7 on 2021-05-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_exammanagerrelation_can_create_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(null=True, upload_to='exam_images'),
        ),
    ]
