# Generated by Django 3.1.7 on 2021-12-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20211218_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-id',)},
        ),
    ]
