# Generated by Django 3.1.7 on 2021-04-29 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0014_auto_20210427_0134'),
        ('evaluation', '0008_auto_20210417_2317'),
        ('teacher', '0002_auto_20210425_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorGlance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Current', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance_evaluator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='GlanceEvaluationsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance_evaluation_category', to='subscription.subscriptionquestioncategory')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_glance', to='evaluation.evaluation')),
                ('glance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glance_evaluation', to='teacher.evaluatorglance')),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('glance', 'evaluation')},
            },
        ),
    ]
