# Generated by Django 3.1.7 on 2021-04-29 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0008_auto_20210417_2317'),
        ('teacher', '0003_evaluatorglance_glanceevaluationsrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glanceevaluationsrecord',
            name='evaluation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_glance', to='evaluation.evaluation'),
        ),
    ]
