# Generated by Django 3.1.7 on 2021-05-15 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0005_auto_20210430_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings_total', models.FloatField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('evaluator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
