# Generated by Django 3.1.7 on 2021-05-15 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0017_delete_subscriptionextras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0006_evaluatorrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorCategoryPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_unique_category', to='subscription.subscriptionquestioncategory')),
                ('evaluator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_pricing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'unique_together': {('evaluator', 'category')},
            },
        ),
    ]
