# Generated by Django 2.1.8 on 2021-03-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20210308_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='media/images/profile'),
        ),
    ]
