# Generated by Django 2.1.8 on 2021-03-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_auto_20210308_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(null=True, upload_to='media_storage/images/profile'),
        ),
    ]
