# Generated by Django 2.1.8 on 2021-03-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_auto_20210309_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isVarified',
            new_name='isVerified',
        ),
    ]
