# Generated by Django 2.1.8 on 2021-04-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0006_auto_20210320_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',)},
        ),
    ]
