# Generated by Django 2.1.8 on 2021-04-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_auto_20210404_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='media_storage/images/profile'),
        ),
    ]
