# Generated by Django 2.1.8 on 2021-04-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_auto_20210406_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',)},
        ),
    ]
