# Generated by Django 3.1.7 on 2021-04-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_auto_20210417_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
            preserve_default=False,
        ),
    ]
