# Generated by Django 3.1.7 on 2021-11-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0014_auto_20210425_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationotp',
            name='otp',
            field=models.TextField(null=True),
        ),
    ]
