# Generated by Django 2.1.8 on 2021-03-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20210308_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
