# Generated by Django 2.1.8 on 2021-03-24 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_auto_20210320_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled', models.BigIntegerField(default=0)),
                ('managers', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionquestionallowence',
            name='secondary_id',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionquestionallowence',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_allowences', to='subscription.Subscription'),
        ),
    ]
