# Generated by Django 2.1.8 on 2021-03-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20210324_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubscriptionrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentsubscriptionsquestionsrecord',
            name='student_subscription',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='StudentSubscriptionRecord',
        ),
        migrations.DeleteModel(
            name='StudentSubscriptionsQuestionsRecord',
        ),
    ]
