# Generated by Django 2.1.8 on 2021-03-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_auto_20210326_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionquestionallowence',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
