# Generated by Django 2.1.8 on 2021-04-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_subscriptionquestionallowence_frequency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-id',)},
        ),
    ]
