# Generated by Django 2.1.8 on 2021-04-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_auto_20210405_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionQuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_cost', models.FloatField(null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptionquestionallowence',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowences_category', to='subscription.SubscriptionQuestionCategory'),
        ),
    ]
