# Generated by Django 3.1.7 on 2021-04-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0011_manageredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageredits',
            name='content_bkp',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
