# Generated by Django 3.1.7 on 2021-04-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_manageredits_content_bkp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionquestioncategory',
            name='name',
            field=models.FloatField(default=0.0),
        ),
    ]
