# Generated by Django 3.1.7 on 2021-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0015_subscriptionpaymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpaymentdetails',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
