# Generated by Django 3.1.7 on 2021-05-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0016_subscriptionpaymentdetails_signature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionExtras',
        ),
    ]
