# Generated by Django 3.1.7 on 2021-05-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210429_2351'),
        ('subscription', '0018_auto_20210515_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpaymentdetails',
            name='subscription_subscribed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payment_details', to='student.studentsubscriptionrecord'),
        ),
        migrations.AlterField(
            model_name='subscriptionpaymentdetails',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_payment_details', to='subscription.subscription'),
        ),
    ]
