# Generated by Django 2.1.8 on 2021-03-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubscriptionrecord',
            name='one_limit',
            field=models.BooleanField(default=False),
        ),
    ]
