# Generated by Django 2.1.8 on 2021-03-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentsubscriptionrecord_one_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubscriptionrecord',
            name='one_limit',
        ),
        migrations.AddField(
            model_name='studentsubscriptionsquestionsrecord',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
    ]
