# Generated by Django 2.1.8 on 2021-04-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_auto_20210410_2222'),
        ('student', '0004_auto_20210405_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubscriptionsquestionsrecord',
            name='caregory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subject_category', to='subscription.SubscriptionQuestionCategory'),
        ),
        migrations.AlterField(
            model_name='studentsubscriptionsquestionsrecord',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
