# Generated by Django 2.1.8 on 2021-04-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210410_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubscriptionsquestionsrecord',
            old_name='caregory',
            new_name='category',
        ),
    ]
