# Generated by Django 3.1.7 on 2021-04-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_exammanagerrelation_can_create_subscription'),
        ('student', '0006_auto_20210417_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscriptionrecord',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_subscribed_exam', to='exam.exam'),
        ),
    ]
