# Generated by Django 3.1.7 on 2021-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20210429_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscriptionrecord',
            name='purchase_time',
            field=models.DateTimeField(null=True),
        ),
    ]
