# Generated by Django 3.1.7 on 2021-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210518_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscriptionrecord',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
