# Generated by Django 2.1.8 on 2021-03-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGlance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=100, null=True)),
                ('text', models.CharField(max_length=100, null=True)),
                ('count', models.BigIntegerField(null=True)),
            ],
        ),
    ]
