# Generated by Django 2.1.8 on 2021-03-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteglance',
            name='count',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
