# Generated by Django 2.1.8 on 2021-03-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0002_auto_20210309_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteglance',
            name='thingname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
