# Generated by Django 3.1.7 on 2021-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0005_noticeboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsnConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_heading', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteGlance',
        ),
    ]
